[pytest]
pythonpath = .
filterwarnings =
    ignore::DeprecationWarning
    ignore:.*Unable to find acceptable character detection dependency.*
    ignore:.*websockets.WebSocketClientProtocol is deprecated.*

