# PortaMind configuration file

quant:
  alpha: 0.7          # Default blending coefficient (0 = all NetWeaver, 1 = all NeuralFusion)
  gross: 1.0          # Total portfolio gross exposure
  w_min: -0.4         # Minimum per-asset weight
  w_max: 0.4          # Maximum per-asset weight

llm:
  model_name: gpt-4o-mini
  timeout: 30

topk:
  default_netweaver: null   # Optional top-k for NetWeaver conversion
  default_final: 10         # Optional top-k for final PortaMind portfolio

logging:
  level: INFO
  file: logs/portamind.log

# -------------------------------
# Master stock universe
# -------------------------------
market:
  benchmark_symbol:
    - SP:SPX
  symbols_usdt:
    - BINANCE:BTCUSDT
    - BINANCE:ETHUSDT
    - BINANCE:BNBUSDT
    - BINANCE:SOLUSDT
    - BINANCE:XRPUSDT
    - NASDAQ:AAPL
    - NASDAQ:MSFT
    - NASDAQ:NVDA
    - NASDAQ:GOOGL
    - NASDAQ:META
    - NASDAQ:AMZN
    - NYSE:CRM
    - NASDAQ:COST
    - NYSE:NOW
    - NYSE:ORCL
    - NASDAQ:AVGO
    - NYSE:TSM
    - NASDAQ:ASML
    - NASDAQ:QCOM
    - NYSE:IBM
    - NYSE:JPM
    - NYSE:BAC
    - NYSE:WFC
    - NYSE:MS
    - NYSE:BRK.A
    - NYSE:XOM
    - NYSE:CVX
    - NYSE:KO
    - NASDAQ:PEP
    - NYSE:MCD
    - SP:SPX
    - TVC:IXIC
    - XETR:DAX
    - TVC:NI225
    - TVC:UKX
    - FX:EURUSD
    - FX_IDC:USDJPY
    - OANDA:XAUUSD
    - BIST:XAGUSD1!
    - CBOE:VIX

clickhouse:
  host: ${CH_HOST}
  port: ${CH_PORT}
  database: ${CH_DB}
  table: ${CH_TABLE}
  user: ${CH_USER}
  password: ${CH_PASS}

mongo:
  host: ${MONGO_HOST}
  port: ${MONGO_PORT}
  database: ${MONGO_DB}
  user: ${MONGO_USER}
  password: ${MONGO_PASS}
  authSource: ${MONGO_AUTHSOURCE}

novo_mongo:
  host: ${NOVO_MONGO_HOST}
  port: ${NOVO_MONGO_PORT}
  database: ${NOVO_MONGO_DB}
  user: ${NOVO_MONGO_USER}
  password: ${NOVO_MONGO_PASS}
  authSource: ${NOVO_MONGO_AUTH_DB}